//! Canonical, synthetic browser fixtures produced from the Rust domain model.
//!
//! This module is feature-gated so production builds do not include fixture
//! generation. The generated bytes are the only source of functional and
//! performance API bodies served by `web/dev/fixture-server.mjs`.

use crate::model::{
    ATLAS_VERSION, Bip110Assessment, Bip110RuleId, Bip110Status, ChainTip, ClassificationProgress,
    ClassificationResult, ClassificationResultState, ClassificationState, MembershipFacts,
    MempoolEntry, MempoolSnapshot, SourceAvailability, SourceSummary, TransactionStructure,
    classifier_catalog,
};
use crate::staged_snapshot::reencode_manifest_for_source;
use crate::staged_snapshot::{EncodedStage, StageKind, encode_staged_snapshot};
use anyhow::{Context, Result, ensure};
use bitcoin::hashes::{Hash, sha256};
use clap::ValueEnum;
use serde::{Deserialize, Serialize};
use serde_json::{Value, json};
use std::collections::BTreeSet;
use std::fs;
use std::path::{Path, PathBuf};
use std::time::{SystemTime, UNIX_EPOCH};

pub const FIXTURE_MANIFEST_VERSION: u64 = 2;
const FUNCTIONAL_SOURCE_COUNT: usize = 3;
const MAX_PERFORMANCE_SOURCES: usize = 4;
const PERFORMANCE_REFERENCE_TIME_MS: u64 = 1_786_000_000_000;
const Q32_SCALE: u64 = 1_u64 << 32;

#[derive(Clone, Copy, Debug, Eq, PartialEq, ValueEnum)]
pub enum FixtureProfile {
    Functional,
    Performance,
}

impl FixtureProfile {
    fn directory_name(self) -> &'static str {
        match self {
            Self::Functional => "functional",
            Self::Performance => "performance",
        }
    }
}

impl std::fmt::Display for FixtureProfile {
    fn fmt(&self, formatter: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        formatter.write_str(self.directory_name())
    }
}

#[derive(Clone, Debug)]
pub struct ExportOptions {
    pub profile: FixtureProfile,
    pub output_root: PathBuf,
    pub transaction_count: usize,
    pub source_count: usize,
}

pub fn write_publication_digest_source_cases(
    output_path: &Path,
    transaction_count: usize,
    source_count: usize,
) -> Result<()> {
    #[derive(Serialize)]
    struct SourceCases {
        schema_version: u64,
        cases: Vec<SourceCase>,
    }

    #[derive(Serialize)]
    struct SourceCase {
        name: &'static str,
        availability: &'static str,
        last_poll_started_at_ms: Option<u64>,
        last_error: Option<&'static str>,
        publication_id: String,
    }

    let (sources, _) = performance_sources(
        PERFORMANCE_REFERENCE_TIME_MS,
        transaction_count,
        source_count,
    )
    .context("build publication digest fixture source")?;
    let source = sources
        .first()
        .context("publication digest fixture source is missing")?;
    let bundle = encode_staged_snapshot(&source.summary, &source.snapshot)
        .context("encode publication digest fixture")?;
    let cases = [
        (
            "ready",
            "ready",
            SourceAvailability::Ready,
            Some(1_785_999_990_000),
            None,
        ),
        (
            "stale_retained_failure",
            "stale",
            SourceAvailability::Stale,
            None,
            Some("Bitcoin node RPC is unavailable"),
        ),
    ];
    let cases = cases
        .into_iter()
        .map(
            |(name, availability_label, availability, last_poll_started_at_ms, last_error)| {
                let mut case_source = bundle.manifest.value.source.clone();
                case_source.availability = availability;
                case_source.last_poll_started_at_ms = last_poll_started_at_ms;
                case_source.last_error = last_error.map(str::to_owned);
                let encoded = reencode_manifest_for_source(&bundle.manifest.value, &case_source)
                    .context("re-encode publication digest source case")?;
                Ok(SourceCase {
                    name,
                    availability: availability_label,
                    last_poll_started_at_ms,
                    last_error,
                    publication_id: encoded.value.publication_id,
                })
            },
        )
        .collect::<Result<Vec<_>>>()?;
    let mut encoded = serde_json::to_vec_pretty(&SourceCases {
        schema_version: 2,
        cases,
    })?;
    encoded.push(b'\n');
    if let Some(parent) = output_path.parent() {
        fs::create_dir_all(parent)
            .with_context(|| format!("create fixture directory {}", parent.display()))?;
    }
    fs::write(output_path, encoded)
        .with_context(|| format!("write source digest fixture {}", output_path.display()))?;
    Ok(())
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct FixtureBody {
    pub path: String,
    pub content_type: String,
    pub uncompressed_bytes: u64,
    pub content_id: String,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct FixtureRoute {
    pub request_path: String,
    pub body: FixtureBody,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct FixtureStage {
    pub kind: String,
    pub classifier_id: Option<String>,
    pub content_id: String,
    pub dependency_ids: Vec<String>,
    pub route: FixtureRoute,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct FixtureSnapshot {
    pub source_id: String,
    pub transaction_count: u64,
    pub total_vsize: u64,
    pub differing_wtxid_count: u64,
    pub publication_id: String,
    pub population_id: String,
    pub classification_set_id: String,
    pub manifest: FixtureRoute,
    pub stages: Vec<FixtureStage>,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct FixtureTransactionDetail {
    pub source_id: String,
    pub txid: String,
    pub route: FixtureRoute,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct FixtureConfiguration {
    pub requested_transaction_count_per_source: usize,
    pub source_count: usize,
    pub common_transaction_share_basis_points: u64,
    pub witness_variant_share_basis_points: u64,
}

#[derive(Clone, Debug, Deserialize, Eq, PartialEq, Serialize)]
pub struct FixtureManifest {
    pub manifest_version: u64,
    pub profile: String,
    pub generated_at_ms: u64,
    pub atlas_version: String,
    pub source_list: FixtureRoute,
    pub snapshots: Vec<FixtureSnapshot>,
    pub transaction_details: Vec<FixtureTransactionDetail>,
    pub configuration: FixtureConfiguration,
    #[serde(skip)]
    pub output_directory: PathBuf,
}

#[derive(Clone, Copy)]
struct TransactionProfile {
    weight: f64,
    labels: &'static [&'static str],
    minimum_vsize: u64,
    maximum_vsize: u64,
}

const TRANSACTION_PROFILES: [TransactionProfile; 8] = [
    TransactionProfile {
        weight: 0.34,
        labels: &["version_2", "has_witness", "p2wpkh"],
        minimum_vsize: 110,
        maximum_vsize: 400,
    },
    TransactionProfile {
        weight: 0.18,
        labels: &["version_2", "has_witness", "p2wsh"],
        minimum_vsize: 150,
        maximum_vsize: 900,
    },
    TransactionProfile {
        weight: 0.22,
        labels: &["version_2", "has_witness", "p2tr", "signals_rbf"],
        minimum_vsize: 111,
        maximum_vsize: 650,
    },
    TransactionProfile {
        weight: 0.10,
        labels: &["version_1", "p2pkh"],
        minimum_vsize: 190,
        maximum_vsize: 1_200,
    },
    TransactionProfile {
        weight: 0.05,
        labels: &["version_2", "p2sh"],
        minimum_vsize: 220,
        maximum_vsize: 2_500,
    },
    TransactionProfile {
        weight: 0.06,
        labels: &["version_2", "has_witness", "p2wpkh", "p2tr"],
        minimum_vsize: 140,
        maximum_vsize: 3_000,
    },
    TransactionProfile {
        weight: 0.03,
        labels: &["version_2", "has_witness", "p2tr", "op_return"],
        minimum_vsize: 130,
        maximum_vsize: 40_000,
    },
    TransactionProfile {
        weight: 0.02,
        labels: &["version_2", "p2a"],
        minimum_vsize: 65,
        maximum_vsize: 120,
    },
];

struct FixtureSource {
    summary: SourceSummary,
    snapshot: MempoolSnapshot,
}

#[derive(Clone, Copy)]
struct FixtureRng {
    state: u32,
}

impl FixtureRng {
    fn new(seed: u32) -> Self {
        Self { state: seed }
    }

    fn next_u32(&mut self) -> u32 {
        self.state = self.state.wrapping_add(0x6d2b_79f5);
        let mut value = self.state;
        value = (value ^ (value >> 15)).wrapping_mul(1 | value);
        value = value.wrapping_add((value ^ (value >> 7)).wrapping_mul(61 | value)) ^ value;
        value ^ (value >> 14)
    }

    fn next(&mut self) -> f64 {
        f64::from(self.next_u32()) / 4_294_967_296.0
    }

    fn integer(&mut self, upper_exclusive: u64) -> u64 {
        (self.next() * upper_exclusive as f64).floor() as u64
    }
}

fn q32_square(value: u32) -> u64 {
    let value = u64::from(value);
    value * value / Q32_SCALE
}

fn scale_q32_rounded(value: u64, upper: u64) -> u64 {
    debug_assert!(value < Q32_SCALE);
    ((u128::from(value) * u128::from(upper) + u128::from(Q32_SCALE / 2)) / u128::from(Q32_SCALE))
        as u64
}

/// Closely approximates x^2.2 without platform-specific libm behavior.
fn vsize_fraction(value: u32) -> u64 {
    let squared = q32_square(value);
    let value = u64::from(value);
    let cubed = squared * value / Q32_SCALE;
    (4 * squared + cubed) / 5
}

/// Closely approximates x^1.6 without platform-specific libm behavior.
fn age_fraction(value: u32) -> u64 {
    let squared = q32_square(value);
    let value = u64::from(value);
    (2 * value + 3 * squared) / 5
}

/// Produces a bounded log-uniform value from 10,000 to just under 655,360,000.
fn synthetic_output_sats(value: u32) -> u64 {
    let scaled = u64::from(value) * 16;
    let exponent = scaled / Q32_SCALE;
    let fraction = scaled % Q32_SCALE;
    let base = 10_000_u64 << exponent;
    base + scale_q32_rounded(fraction, base)
}

pub fn export(options: ExportOptions) -> Result<FixtureManifest> {
    validate_options(&options)?;
    let generated_at_ms = unix_time_ms()?;
    let (sources, configuration) = match options.profile {
        FixtureProfile::Functional => functional_sources(generated_at_ms)?,
        FixtureProfile::Performance => performance_sources(
            PERFORMANCE_REFERENCE_TIME_MS,
            options.transaction_count,
            options.source_count,
        )?,
    };
    let output_directory = options.output_root.join(options.profile.directory_name());
    replace_directory(&output_directory)?;

    let source_summaries = sources
        .iter()
        .map(|source| source.summary.clone())
        .collect::<Vec<_>>();
    let sources_bytes = serde_json::to_vec(&json!({
        "atlas_version": ATLAS_VERSION,
        "sources": source_summaries,
    }))?;
    let source_list = write_route(
        &output_directory,
        "/api/v2/sources",
        "sources.json",
        &sources_bytes,
    )?;

    let mut snapshots = Vec::with_capacity(sources.len());
    let mut transaction_details = Vec::new();
    for source in &sources {
        let bundle = encode_staged_snapshot(&source.summary, &source.snapshot)?;
        let manifest_path = format!("snapshots/{}/manifest.json", source.snapshot.source_id);
        let manifest_route = write_route(
            &output_directory,
            &format!("/api/v2/sources/{}/mempool", source.snapshot.source_id),
            &manifest_path,
            &bundle.manifest.bytes,
        )?;
        ensure!(
            manifest_route.body.content_id == bundle.manifest.content_id,
            "fixture manifest digest does not match staged manifest"
        );
        let publication_id = bundle.manifest.value.publication_id.clone();
        let population_id = bundle.manifest.value.population_id.clone();
        let classification_set_id = bundle.manifest.value.classification_set_id.clone();
        let stage_routes = std::iter::once(bundle.population)
            .chain(std::iter::once(bundle.membership))
            .chain(std::iter::once(bundle.structure))
            .chain(bundle.classifier_stages)
            .map(|stage| write_stage(&output_directory, &source.snapshot.source_id, stage))
            .collect::<Result<Vec<_>>>()?;
        snapshots.push(FixtureSnapshot {
            source_id: source.snapshot.source_id.clone(),
            transaction_count: source.snapshot.transaction_count,
            total_vsize: source.snapshot.total_vsize,
            differing_wtxid_count: u64::try_from(
                source
                    .snapshot
                    .transactions
                    .iter()
                    .filter(|entry| entry.txid != entry.wtxid)
                    .count(),
            )
            .context("differing wtxid count is too large")?,
            publication_id,
            population_id,
            classification_set_id,
            manifest: manifest_route,
            stages: stage_routes,
        });

        if options.profile == FixtureProfile::Functional {
            for entry in source
                .snapshot
                .transactions
                .iter()
                .filter(|entry| entry.bip110.is_some())
            {
                let detail_path = format!(
                    "transactions/{}/{}.json",
                    source.snapshot.source_id, entry.txid
                );
                let detail_bytes = transaction_detail_bytes(&source.snapshot, entry)?;
                let detail_body = write_body(&output_directory, &detail_path, &detail_bytes)?;
                transaction_details.push(FixtureTransactionDetail {
                    source_id: source.snapshot.source_id.clone(),
                    txid: entry.txid.clone(),
                    route: FixtureRoute {
                        request_path: format!(
                            "/api/v2/sources/{}/transactions/{}",
                            source.snapshot.source_id, entry.txid
                        ),
                        body: detail_body,
                    },
                });
            }
        }
    }

    let mut manifest = FixtureManifest {
        manifest_version: FIXTURE_MANIFEST_VERSION,
        profile: options.profile.to_string(),
        generated_at_ms,
        atlas_version: ATLAS_VERSION.to_owned(),
        source_list,
        snapshots,
        transaction_details,
        configuration,
        output_directory: output_directory.clone(),
    };
    validate_manifest(&manifest, options.profile)?;
    let manifest_bytes = serde_json::to_vec_pretty(&manifest)?;
    fs::write(output_directory.join("manifest.json"), manifest_bytes)
        .with_context(|| format!("write {}/manifest.json", output_directory.display()))?;
    manifest.output_directory = output_directory;
    Ok(manifest)
}

fn validate_options(options: &ExportOptions) -> Result<()> {
    ensure!(
        options.transaction_count > 0,
        "transaction count must be positive"
    );
    ensure!(
        (1..=MAX_PERFORMANCE_SOURCES).contains(&options.source_count),
        "source count must be between 1 and {MAX_PERFORMANCE_SOURCES}"
    );
    Ok(())
}

fn unix_time_ms() -> Result<u64> {
    let duration = SystemTime::now()
        .duration_since(UNIX_EPOCH)
        .context("system clock is before the Unix epoch")?;
    u64::try_from(duration.as_millis()).context("current time does not fit in u64 milliseconds")
}

fn replace_directory(path: &Path) -> Result<()> {
    if path.exists() {
        fs::remove_dir_all(path)
            .with_context(|| format!("remove old fixture directory {}", path.display()))?;
    }
    fs::create_dir_all(path).with_context(|| format!("create {}", path.display()))
}

fn write_body(output_directory: &Path, relative_path: &str, bytes: &[u8]) -> Result<FixtureBody> {
    let path = output_directory.join(relative_path);
    if let Some(parent) = path.parent() {
        fs::create_dir_all(parent).with_context(|| format!("create {}", parent.display()))?;
    }
    fs::write(&path, bytes).with_context(|| format!("write {}", path.display()))?;
    Ok(FixtureBody {
        path: relative_path.to_owned(),
        content_type: "application/json".to_owned(),
        uncompressed_bytes: u64::try_from(bytes.len()).context("fixture body is too large")?,
        content_id: sha256::Hash::hash(bytes).to_string(),
    })
}

fn write_route(
    output_directory: &Path,
    request_path: &str,
    relative_path: &str,
    bytes: &[u8],
) -> Result<FixtureRoute> {
    Ok(FixtureRoute {
        request_path: request_path.to_owned(),
        body: write_body(output_directory, relative_path, bytes)?,
    })
}

fn write_stage(
    output_directory: &Path,
    source_id: &str,
    stage: EncodedStage,
) -> Result<FixtureStage> {
    let kind = stage_kind_name(stage.descriptor.kind);
    let classifier_component = stage
        .descriptor
        .classifier_id
        .as_deref()
        .map(|classifier_id| format!("/{classifier_id}"))
        .unwrap_or_default();
    let request_path = format!(
        "/api/v2/sources/{source_id}/mempool/stages/{kind}{classifier_component}/{}",
        stage.descriptor.content_id
    );
    let file_name = match stage.descriptor.classifier_id.as_deref() {
        Some(classifier_id) => format!(
            "snapshots/{source_id}/stages/classifier-{classifier_id}-{}.json",
            stage.descriptor.content_id
        ),
        None => format!(
            "snapshots/{source_id}/stages/{kind}-{}.json",
            stage.descriptor.content_id
        ),
    };
    let route = write_route(output_directory, &request_path, &file_name, &stage.bytes)?;
    ensure!(
        route.body.content_id == stage.descriptor.content_id,
        "fixture stage digest does not match descriptor"
    );
    Ok(FixtureStage {
        kind: kind.to_owned(),
        classifier_id: stage.descriptor.classifier_id,
        content_id: stage.descriptor.content_id,
        dependency_ids: stage.descriptor.dependency_ids,
        route,
    })
}

fn stage_kind_name(kind: StageKind) -> &'static str {
    match kind {
        StageKind::Population => "population",
        StageKind::Membership => "membership",
        StageKind::Structure => "structure",
        StageKind::Classifier => "classifier",
    }
}

fn validate_manifest(manifest: &FixtureManifest, profile: FixtureProfile) -> Result<()> {
    ensure!(
        manifest.manifest_version == FIXTURE_MANIFEST_VERSION,
        "unsupported fixture manifest version"
    );
    ensure!(manifest.profile == profile.to_string(), "profile mismatch");
    ensure!(!manifest.snapshots.is_empty(), "fixture has no snapshots");
    ensure!(
        manifest.configuration.source_count == manifest.snapshots.len(),
        "fixture source count does not match its snapshots"
    );
    ensure!(
        manifest.source_list.request_path == "/api/v2/sources",
        "fixture source-list route is not v2"
    );
    for snapshot in &manifest.snapshots {
        ensure!(
            snapshot.manifest.request_path
                == format!("/api/v2/sources/{}/mempool", snapshot.source_id),
            "fixture manifest route is not v2"
        );
        ensure!(
            snapshot.stages.len() == classifier_catalog().len() + 3,
            "fixture snapshot is missing v2 stages"
        );
        ensure!(
            snapshot
                .stages
                .iter()
                .all(|stage| stage.route.request_path.starts_with("/api/v2/")),
            "fixture stage route is not v2"
        );
    }
    ensure!(
        manifest
            .transaction_details
            .iter()
            .all(|detail| detail.route.request_path.starts_with("/api/v2/")),
        "fixture detail route is not v2"
    );
    if profile == FixtureProfile::Functional {
        ensure!(
            manifest.snapshots.len() == FUNCTIONAL_SOURCE_COUNT,
            "functional fixtures require exactly three sources"
        );
        ensure!(
            !manifest.transaction_details.is_empty(),
            "functional fixtures require transaction detail bodies"
        );
    }
    Ok(())
}

fn functional_sources(now_ms: u64) -> Result<(Vec<FixtureSource>, FixtureConfiguration)> {
    let pool = unique_txids(1_000, 0x0a_71_a5);
    let common = &pool[0..560];
    let core_only = &pool[560..700];
    let knots_only = &pool[700..840];
    let stale = &pool[300..720];
    let tip = ChainTip {
        height: 917_432,
        hash: deterministic_hash(0x07ea),
    };
    let stale_tip = ChainTip {
        height: 917_429,
        hash: deterministic_hash(0x07eb),
    };
    let definitions = [
        (
            "vps-core-01",
            "vps-core-01",
            [common, core_only].concat(),
            0x0005_1ee7,
            42_000,
            tip.clone(),
            SourceAvailability::Ready,
            ClassificationState::Complete,
            None,
        ),
        (
            "vps-knots-01",
            "vps-knots-01",
            [common, knots_only].concat(),
            0x000b_0a17,
            21_000,
            tip,
            SourceAvailability::Ready,
            ClassificationState::Complete,
            None,
        ),
        (
            "fixture-stale-01",
            "fixture-stale-01",
            stale.to_vec(),
            0x0009_a44a,
            1_260_000,
            stale_tip,
            SourceAvailability::Stale,
            ClassificationState::Paused,
            Some("transport error: connection refused (os error 61)".to_owned()),
        ),
    ];
    let mut sources = Vec::with_capacity(definitions.len());
    for (
        source_id,
        source_label,
        txids,
        seed,
        observed_offset,
        chain_tip,
        availability,
        classification_state,
        last_error,
    ) in definitions
    {
        sources.push(build_source(
            source_id,
            source_label,
            &txids,
            seed,
            now_ms.saturating_sub(observed_offset),
            now_ms.saturating_sub(15_000),
            chain_tip,
            availability,
            classification_state,
            last_error,
            0.98,
        )?);
    }
    Ok((
        sources,
        FixtureConfiguration {
            requested_transaction_count_per_source: 700,
            source_count: FUNCTIONAL_SOURCE_COUNT,
            common_transaction_share_basis_points: 8_000,
            witness_variant_share_basis_points: 9_800,
        },
    ))
}

fn performance_sources(
    now_ms: u64,
    transaction_count: usize,
    source_count: usize,
) -> Result<(Vec<FixtureSource>, FixtureConfiguration)> {
    let common_count = transaction_count.saturating_mul(8) / 10;
    let unique_count = transaction_count.saturating_sub(common_count);
    let pool_size = common_count
        .checked_add(unique_count.saturating_mul(source_count))
        .context("performance fixture pool size overflow")?;
    let pool = unique_txids(pool_size, 0x0f_3e_71);
    let mut sources = Vec::with_capacity(source_count);
    for index in 0..source_count {
        let unique_start = common_count + index * unique_count;
        let mut txids = Vec::with_capacity(transaction_count);
        txids.extend_from_slice(&pool[..common_count]);
        txids.extend_from_slice(&pool[unique_start..unique_start + unique_count]);
        let source_number = index + 1;
        let source_id = format!("perf-node-{source_number:02}");
        sources.push(build_source(
            &source_id,
            &source_id,
            &txids,
            0x51ee_7000_u32.wrapping_add(index as u32 * 0x1021),
            now_ms.saturating_sub(20_000 + index as u64 * 7_000),
            now_ms.saturating_sub(10_000),
            ChainTip {
                height: 917_432,
                hash: deterministic_hash(0x07ea),
            },
            SourceAvailability::Ready,
            ClassificationState::Complete,
            None,
            0.55,
        )?);
    }
    Ok((
        sources,
        FixtureConfiguration {
            requested_transaction_count_per_source: transaction_count,
            source_count,
            common_transaction_share_basis_points: 8_000,
            witness_variant_share_basis_points: 5_500,
        },
    ))
}

#[allow(clippy::too_many_arguments)]
fn build_source(
    source_id: &str,
    source_label: &str,
    txids: &[String],
    seed: u32,
    observed_at_ms: u64,
    last_poll_started_at_ms: u64,
    chain_tip: ChainTip,
    availability: SourceAvailability,
    classification_state: ClassificationState,
    last_error: Option<String>,
    differing_wtxid_probability: f64,
) -> Result<FixtureSource> {
    let mut rng = FixtureRng::new(seed);
    let mut transactions = txids
        .iter()
        .map(|txid| make_entry(txid, &mut rng, observed_at_ms, differing_wtxid_probability))
        .collect::<Result<Vec<_>>>()?;
    transactions.sort_unstable_by(|left, right| left.txid.cmp(&right.txid));
    let snapshot = MempoolSnapshot::new_with_collection_window(
        source_id.to_owned(),
        source_label.to_owned(),
        observed_at_ms.saturating_sub(1_800),
        observed_at_ms,
        1_800,
        chain_tip,
        transactions,
    )?
    .with_classification_revision(7)?;
    let summary = SourceSummary {
        source_id: source_id.to_owned(),
        source_label: source_label.to_owned(),
        availability,
        poll_interval_seconds: 60,
        last_poll_started_at_ms: Some(last_poll_started_at_ms),
        snapshot_observed_at_ms: Some(snapshot.observed_at_ms),
        chain_tip: Some(snapshot.chain_tip.clone()),
        transaction_count: Some(snapshot.transaction_count),
        total_vsize: Some(snapshot.total_vsize),
        classification: Some(ClassificationProgress {
            state: classification_state,
            revision: snapshot.classification_revision,
            classified_count: snapshot.transaction_count
                - snapshot.bip110_summary.unclassified_count,
            unclassified_count: snapshot.bip110_summary.unclassified_count,
        }),
        last_error,
    };
    Ok(FixtureSource { summary, snapshot })
}

fn make_entry(
    txid: &str,
    rng: &mut FixtureRng,
    observed_at_ms: u64,
    differing_wtxid_probability: f64,
) -> Result<MempoolEntry> {
    let profile = pick_profile(rng);
    let vsize = (profile.minimum_vsize
        + scale_q32_rounded(
            vsize_fraction(rng.next_u32()),
            profile.maximum_vsize - profile.minimum_vsize,
        ))
    .max(65);
    let fee_sats = (vsize as f64 * fee_rate(rng)).round() as u64;
    let fee_sats = fee_sats.max(vsize);
    let entered_at_ms =
        observed_at_ms.saturating_sub(scale_q32_rounded(age_fraction(rng.next_u32()), 172_800_000));
    let has_relatives = rng.next() < 0.18;
    let ancestor_extra = if has_relatives {
        (rng.next() * 3.0).round() as u64
    } else {
        0
    };
    let descendant_extra = if has_relatives && rng.next() < 0.5 {
        (rng.next() * 4.0).round() as u64
    } else {
        0
    };
    let facts = MembershipFacts {
        weight: (vsize * 4).saturating_sub(rng.integer(3)).max(1),
        ancestor_count: 1 + ancestor_extra,
        ancestor_vsize: vsize + ancestor_extra * (120.0 + rng.next() * 800.0).round() as u64,
        ancestor_fee_sats: i64::try_from(
            fee_sats + ancestor_extra * (200.0 + rng.next() * 4_000.0).round() as u64,
        )?,
        descendant_count: 1 + descendant_extra,
        descendant_vsize: vsize + descendant_extra * (120.0 + rng.next() * 800.0).round() as u64,
        replaceable: rng.next() < 0.35,
    };
    let wtxid = if rng.next() < differing_wtxid_probability {
        hex64(rng)
    } else {
        txid.to_owned()
    };
    let mut entry = MempoolEntry::new_variant(
        txid.to_owned(),
        wtxid,
        vsize,
        fee_sats,
        entered_at_ms,
        facts,
    )?;
    if rng.next() < 0.02 {
        return Ok(entry);
    }

    let data_labels = data_labels(rng.next());
    let mut property_labels = profile
        .labels
        .iter()
        .map(|label| (*label).to_owned())
        .collect::<Vec<_>>();
    if data_labels.iter().any(|label| {
        matches!(
            *label,
            "other_op_return" | "runes" | "counterparty" | "omni"
        )
    }) && !property_labels.iter().any(|label| label == "op_return")
    {
        property_labels.push("op_return".to_owned());
    }
    if data_labels
        .iter()
        .any(|label| matches!(*label, "inscription" | "brc20"))
        && !property_labels.iter().any(|label| label == "has_witness")
    {
        property_labels.push("has_witness".to_owned());
    }
    let property_order = classifier_catalog()[0]
        .labels
        .iter()
        .map(|label| label.key.clone())
        .collect::<Vec<_>>();
    property_labels.sort_by_key(|label| {
        property_order
            .iter()
            .position(|candidate| candidate == label)
            .unwrap_or(usize::MAX)
    });
    let partial_properties = rng.next() < 0.07;
    let shape_label = shape_label(rng.next(), partial_properties);
    let shape_labels = if partial_properties && shape_label == "other_shape" {
        Vec::new()
    } else {
        vec![shape_label.to_owned()]
    };
    let (assessment, policy_result) = policy_result(rng);
    let missing_facts = if partial_properties {
        vec!["input_script_pubkeys".to_owned()]
    } else {
        Vec::new()
    };
    entry.classifications = vec![
        classification_result(
            "transaction_properties",
            partial_properties,
            property_labels.clone(),
            None,
            missing_facts.clone(),
        ),
        classification_result(
            "transaction_shape",
            partial_properties,
            shape_labels.clone(),
            shape_labels.first().cloned(),
            missing_facts,
        ),
        classification_result(
            "data_protocols",
            false,
            data_labels
                .iter()
                .map(|label| (*label).to_owned())
                .collect(),
            Some(data_labels[0].to_owned()),
            Vec::new(),
        ),
        policy_result,
    ];
    entry.bip110 = Some(assessment);
    entry.structure = Some(transaction_structure(
        rng,
        vsize,
        shape_label,
        &data_labels,
        property_labels.iter().any(|label| label == "has_witness"),
    )?);
    Ok(entry)
}

fn pick_profile(rng: &mut FixtureRng) -> TransactionProfile {
    let total = TRANSACTION_PROFILES
        .iter()
        .map(|profile| profile.weight)
        .sum::<f64>();
    let mut roll = rng.next() * total;
    for profile in TRANSACTION_PROFILES {
        roll -= profile.weight;
        if roll <= 0.0 {
            return profile;
        }
    }
    TRANSACTION_PROFILES[TRANSACTION_PROFILES.len() - 1]
}

fn fee_rate(rng: &mut FixtureRng) -> f64 {
    let roll = rng.next();
    if roll < 0.45 {
        1.0 + rng.next() * 3.0
    } else if roll < 0.8 {
        4.0 + rng.next() * 20.0
    } else if roll < 0.95 {
        24.0 + rng.next() * 80.0
    } else {
        100.0 + rng.next() * 380.0
    }
}

fn data_labels(roll: f64) -> Vec<&'static str> {
    if roll < 0.70 {
        vec!["no_detected_protocol"]
    } else if roll < 0.78 {
        vec!["other_op_return"]
    } else if roll < 0.85 {
        vec!["runes"]
    } else if roll < 0.91 {
        vec!["inscription"]
    } else if roll < 0.94 {
        vec!["inscription", "brc20"]
    } else if roll < 0.96 {
        vec!["stamps"]
    } else if roll < 0.98 {
        vec!["counterparty"]
    } else {
        vec!["omni"]
    }
}

fn shape_label(roll: f64, partial_properties: bool) -> &'static str {
    if roll < 0.08 && !partial_properties {
        "possible_coinjoin"
    } else if roll < 0.25 {
        "consolidation"
    } else if roll < 0.42 {
        "batch_payout"
    } else {
        "other_shape"
    }
}

fn classification_result(
    classifier_id: &str,
    partial: bool,
    labels: Vec<String>,
    primary_label: Option<String>,
    missing_facts: Vec<String>,
) -> ClassificationResult {
    ClassificationResult {
        classifier_id: classifier_id.to_owned(),
        state: if partial {
            ClassificationResultState::Partial
        } else {
            ClassificationResultState::Complete
        },
        primary_label,
        labels,
        missing_facts,
        evidence: None,
    }
}

fn policy_result(rng: &mut FixtureRng) -> (Bip110Assessment, ClassificationResult) {
    let roll = rng.next();
    if roll < 0.90 {
        let assessment = Bip110Assessment {
            status: Bip110Status::Compatible,
            primary_rule: None,
            violated_rules: Vec::new(),
            unknown_rules: Vec::new(),
        };
        let result = classification_result(
            "knots_bip110",
            false,
            vec!["compatible".to_owned()],
            Some("compatible".to_owned()),
            Vec::new(),
        );
        (assessment, result)
    } else if roll < 0.96 {
        let violated_rules = if rng.next() < 0.70 {
            vec![Bip110RuleId::ElementSize]
        } else {
            vec![Bip110RuleId::OutputSize, Bip110RuleId::ElementSize]
        };
        let unknown_rules = if rng.next() < 0.25 {
            vec![Bip110RuleId::OpSuccess]
        } else {
            Vec::new()
        };
        let partial = !unknown_rules.is_empty();
        let assessment = Bip110Assessment {
            status: Bip110Status::Violating,
            primary_rule: violated_rules.first().copied(),
            violated_rules,
            unknown_rules,
        };
        let result = classification_result(
            "knots_bip110",
            partial,
            vec!["violating".to_owned()],
            Some("violating".to_owned()),
            if partial {
                vec!["policy_facts".to_owned()]
            } else {
                Vec::new()
            },
        );
        (assessment, result)
    } else {
        let unknown_rule = if rng.next() < 0.5 {
            Bip110RuleId::OpSuccess
        } else {
            Bip110RuleId::TapscriptOpIf
        };
        let assessment = Bip110Assessment {
            status: Bip110Status::Indeterminate,
            primary_rule: None,
            violated_rules: Vec::new(),
            unknown_rules: vec![unknown_rule],
        };
        let result = classification_result(
            "knots_bip110",
            true,
            vec!["indeterminate".to_owned()],
            Some("indeterminate".to_owned()),
            vec!["policy_facts".to_owned()],
        );
        (assessment, result)
    }
}

fn transaction_structure(
    rng: &mut FixtureRng,
    vsize: u64,
    shape_label: &str,
    data_labels: &[&str],
    has_witness: bool,
) -> Result<TransactionStructure> {
    let (input_count, output_count) = match shape_label {
        "possible_coinjoin" => (5 + rng.integer(8), 5 + rng.integer(8)),
        "consolidation" => {
            let outputs = 1 + rng.integer(4);
            (outputs * 5 + rng.integer(30), outputs)
        }
        "batch_payout" => {
            let inputs = 1 + rng.integer(3);
            (inputs, inputs * 5 + rng.integer(90))
        }
        _ => (1 + rng.integer(4), 1 + rng.integer(4)),
    };
    let op_return_bytes = match data_labels[0] {
        "other_op_return" => 8 + rng.integer(220),
        "runes" => 12 + rng.integer(40),
        "counterparty" => 16 + rng.integer(120),
        "omni" => 8 + rng.integer(60),
        _ => 0,
    };
    let output_sats = synthetic_output_sats(rng.next_u32());
    let witness_bytes = if has_witness {
        (vsize as f64 * (0.5 + rng.next() * 1.2)).round() as u64
    } else {
        0
    };
    Ok(TransactionStructure::new(
        input_count,
        output_count,
        op_return_bytes,
        output_sats,
        witness_bytes,
    )?)
}

fn transaction_detail_bytes(snapshot: &MempoolSnapshot, entry: &MempoolEntry) -> Result<Vec<u8>> {
    let assessment = entry
        .bip110
        .as_ref()
        .context("detail fixture transaction is unclassified")?;
    let classifications = entry
        .classifications
        .iter()
        .cloned()
        .map(|mut result| {
            result.evidence = Some(json!({
                "observed_labels": &result.labels,
                "missing_facts": &result.missing_facts,
            }));
            result
        })
        .collect::<Vec<_>>();
    let rules = Bip110RuleId::ALL
        .iter()
        .map(|rule| {
            let violated = assessment.violated_rules.contains(rule);
            let unknown = assessment.unknown_rules.contains(rule);
            json!({
                "rule": rule,
                "number": rule.number(),
                "verdict": if violated { "violate" } else if unknown { "unknown" } else { "pass" },
                "evidence_count": u8::from(violated),
                "evidence": if violated { vec![synthetic_rule_evidence(*rule)] } else { Vec::new() },
                "missing_count": u8::from(unknown),
                "missing": if unknown { vec![json!({ "missing": "script_pub_key", "input": 0 })] } else { Vec::new() },
            })
        })
        .collect::<Vec<Value>>();
    Ok(serde_json::to_vec(&json!({
        "source_id": snapshot.source_id,
        "snapshot_observed_at_ms": snapshot.observed_at_ms,
        "classification_revision": snapshot.classification_revision,
        "txid": entry.txid,
        "wtxid": entry.wtxid,
        "classifications": classifications,
        "assessment": assessment,
        "rules": rules,
    }))?)
}

fn synthetic_rule_evidence(rule: Bip110RuleId) -> Value {
    match rule {
        Bip110RuleId::OutputSize => json!({
            "kind": "output_script_too_large",
            "vout": 0,
            "len": 84,
            "is_op_return": true,
            "limit": 83,
        }),
        Bip110RuleId::ElementSize => json!({
            "kind": "witness_item_too_large",
            "input": 0,
            "item_index": 0,
            "len": 257,
            "limit": 256,
        }),
        Bip110RuleId::UndefinedVersion => json!({
            "kind": "undefined_witness_version",
            "input": 0,
            "version": 2,
            "p2sh_wrapped": false,
            "p2a_non_empty_witness": false,
        }),
        Bip110RuleId::TaprootAnnex => json!({
            "kind": "taproot_annex_present",
            "input": 0,
            "annex_len": 1,
        }),
        Bip110RuleId::ControlBlockSize => json!({
            "kind": "control_block_too_large",
            "input": 0,
            "len": 289,
            "depth": 8,
            "limit": 257,
        }),
        Bip110RuleId::OpSuccess => json!({
            "kind": "op_success_present",
            "input": 0,
            "opcode": 80,
            "opcode_pos": 0,
        }),
        Bip110RuleId::TapscriptOpIf => json!({
            "kind": "tapscript_op_if",
            "input": 0,
            "opcode": 99,
            "opcode_pos": 0,
        }),
    }
}

fn unique_txids(count: usize, seed: u32) -> Vec<String> {
    let mut rng = FixtureRng::new(seed);
    let mut values = BTreeSet::new();
    while values.len() < count {
        values.insert(hex64(&mut rng));
    }
    values.into_iter().collect()
}

fn deterministic_hash(seed: u32) -> String {
    hex64(&mut FixtureRng::new(seed))
}

fn hex64(rng: &mut FixtureRng) -> String {
    const HEX: &[u8; 16] = b"0123456789abcdef";
    let mut output = String::with_capacity(64);
    for _ in 0..64 {
        output.push(char::from(HEX[rng.integer(16) as usize]));
    }
    output
}

#[cfg(test)]
mod tests {
    use super::*;

    #[derive(Deserialize)]
    struct PublicationDigestSourceCases {
        schema_version: u64,
        cases: Vec<PublicationDigestSourceCase>,
    }

    #[derive(Deserialize)]
    struct PublicationDigestSourceCase {
        name: String,
        availability: String,
        last_poll_started_at_ms: Option<u64>,
        last_error: Option<String>,
        publication_id: String,
    }

    #[test]
    fn committed_publication_digest_fixture_matches_rust_export() {
        let (sources, _) = performance_sources(PERFORMANCE_REFERENCE_TIME_MS, 3, 1)
            .expect("publication digest fixture source");
        let source = sources.first().expect("publication digest fixture source");
        let bundle = encode_staged_snapshot(&source.summary, &source.snapshot)
            .expect("publication digest fixture encoding");

        assert_eq!(
            bundle.manifest.bytes.as_ref(),
            include_bytes!("../tests/fixtures/publication-digest-v2.json")
        );
    }

    #[test]
    fn publication_digest_source_cases_match_rust_preimages() {
        let (sources, _) = performance_sources(PERFORMANCE_REFERENCE_TIME_MS, 3, 1)
            .expect("publication digest fixture source");
        let source = sources.first().expect("publication digest fixture source");
        let bundle = encode_staged_snapshot(&source.summary, &source.snapshot)
            .expect("publication digest fixture encoding");
        let fixture = serde_json::from_slice::<PublicationDigestSourceCases>(include_bytes!(
            "../tests/fixtures/publication-digest-source-cases-v2.json"
        ))
        .expect("publication digest source cases");
        assert_eq!(fixture.schema_version, 2);
        assert_eq!(
            fixture
                .cases
                .iter()
                .map(|case| case.name.as_str())
                .collect::<Vec<_>>(),
            ["ready", "stale_retained_failure"]
        );

        for case in fixture.cases {
            let mut case_source = bundle.manifest.value.source.clone();
            case_source.availability = match case.availability.as_str() {
                "ready" => SourceAvailability::Ready,
                "stale" => SourceAvailability::Stale,
                value => panic!("unexpected availability {value:?} in {}", case.name),
            };
            case_source.last_poll_started_at_ms = case.last_poll_started_at_ms;
            case_source.last_error = case.last_error;
            let encoded = reencode_manifest_for_source(&bundle.manifest.value, &case_source)
                .expect("re-encoded source case");

            assert_eq!(
                encoded.value.publication_id, case.publication_id,
                "{} publication digest",
                case.name
            );
        }
    }

    #[test]
    fn synthetic_distribution_curves_are_fixed_and_bounded() {
        let samples = [0, 1 << 30, 1 << 31, 3 << 30, u32::MAX];
        let vsize_values = samples.map(vsize_fraction);
        let age_values = samples.map(age_fraction);

        assert_eq!(vsize_values[0], 0);
        assert_eq!(age_values[0], 0);
        assert_eq!(vsize_values[2], 966_367_641);
        assert_eq!(age_values[2], 1_503_238_553);
        assert!(vsize_values.windows(2).all(|pair| pair[0] < pair[1]));
        assert!(age_values.windows(2).all(|pair| pair[0] < pair[1]));
        assert!(vsize_values[4] < Q32_SCALE);
        assert!(age_values[4] < Q32_SCALE);
        assert_eq!(synthetic_output_sats(0), 10_000);
        assert_eq!(synthetic_output_sats(1 << 31), 2_560_000);
        assert!(synthetic_output_sats(u32::MAX) < 655_360_000);
    }

    fn temporary_output_root(test_name: &str) -> PathBuf {
        std::env::temp_dir().join(format!(
            "mempool-atlas-{test_name}-{}-{}",
            std::process::id(),
            unix_time_ms().expect("fixture test time")
        ))
    }

    #[test]
    fn functional_export_has_current_manifest_and_all_contract_bodies() {
        let output_root = temporary_output_root("functional-fixtures");
        let manifest = export(ExportOptions {
            profile: FixtureProfile::Functional,
            output_root: output_root.clone(),
            transaction_count: 1,
            source_count: 1,
        })
        .expect("functional fixture export");

        assert_eq!(manifest.manifest_version, FIXTURE_MANIFEST_VERSION);
        assert_eq!(manifest.snapshots.len(), FUNCTIONAL_SOURCE_COUNT);
        let transaction_count = manifest
            .snapshots
            .iter()
            .map(|snapshot| snapshot.transaction_count)
            .sum::<u64>();
        assert!(
            u64::try_from(manifest.transaction_details.len())
                .expect("fixture detail count fits u64")
                > transaction_count * 9 / 10
        );
        assert!(manifest.output_directory.join("manifest.json").is_file());
        assert!(
            manifest
                .output_directory
                .join(&manifest.source_list.body.path)
                .is_file()
        );
        for snapshot in &manifest.snapshots {
            assert!(
                manifest
                    .output_directory
                    .join(&snapshot.manifest.body.path)
                    .is_file()
            );
            assert_eq!(snapshot.stages.len(), classifier_catalog().len() + 3);
            assert!(snapshot.stages.iter().all(|stage| {
                manifest
                    .output_directory
                    .join(&stage.route.body.path)
                    .is_file()
            }));
        }
        assert!(
            manifest
                .transaction_details
                .iter()
                .all(|detail| detail.route.request_path.starts_with("/api/v2/"))
        );
        for detail in &manifest.transaction_details {
            let body = fs::read(manifest.output_directory.join(&detail.route.body.path))
                .expect("read transaction detail fixture");
            assert!(
                !body
                    .windows(br#"\"fixture\":true"#.len())
                    .any(|window| window == br#"\"fixture\":true"#),
                "transaction detail fixtures must contain presentable evidence"
            );
        }
        fs::remove_dir_all(output_root).expect("remove functional fixture test output");
    }

    #[test]
    fn performance_export_honors_small_test_configuration() {
        let output_root = temporary_output_root("performance-fixtures");
        let manifest = export(ExportOptions {
            profile: FixtureProfile::Performance,
            output_root: output_root.clone(),
            transaction_count: 32,
            source_count: 2,
        })
        .expect("performance fixture export");

        assert_eq!(manifest.snapshots.len(), 2);
        assert!(
            manifest
                .snapshots
                .iter()
                .all(|snapshot| snapshot.transaction_count == 32)
        );
        assert!(manifest.transaction_details.is_empty());
        fs::remove_dir_all(output_root).expect("remove performance fixture test output");
    }

    #[test]
    fn performance_api_bodies_are_reproducible_across_exports() {
        let first_root = temporary_output_root("performance-fixtures-first");
        let second_root = temporary_output_root("performance-fixtures-second");
        let first = export(ExportOptions {
            profile: FixtureProfile::Performance,
            output_root: first_root.clone(),
            transaction_count: 32,
            source_count: 2,
        })
        .expect("first performance fixture export");
        let second = export(ExportOptions {
            profile: FixtureProfile::Performance,
            output_root: second_root.clone(),
            transaction_count: 32,
            source_count: 2,
        })
        .expect("second performance fixture export");

        assert_eq!(
            first.source_list.body.content_id,
            second.source_list.body.content_id
        );
        assert_eq!(
            first
                .snapshots
                .iter()
                .map(|snapshot| {
                    (
                        snapshot.manifest.body.content_id.as_str(),
                        snapshot
                            .stages
                            .iter()
                            .map(|stage| stage.route.body.content_id.as_str())
                            .collect::<Vec<_>>(),
                    )
                })
                .collect::<Vec<_>>(),
            second
                .snapshots
                .iter()
                .map(|snapshot| {
                    (
                        snapshot.manifest.body.content_id.as_str(),
                        snapshot
                            .stages
                            .iter()
                            .map(|stage| stage.route.body.content_id.as_str())
                            .collect::<Vec<_>>(),
                    )
                })
                .collect::<Vec<_>>(),
        );
        fs::remove_dir_all(first_root).expect("remove first fixture output");
        fs::remove_dir_all(second_root).expect("remove second fixture output");
    }

    #[test]
    fn incompatible_manifest_version_is_rejected() {
        let manifest = FixtureManifest {
            manifest_version: FIXTURE_MANIFEST_VERSION + 1,
            profile: FixtureProfile::Functional.to_string(),
            generated_at_ms: 0,
            atlas_version: ATLAS_VERSION.to_owned(),
            source_list: FixtureRoute {
                request_path: "/api/v2/sources".to_owned(),
                body: FixtureBody {
                    path: "sources.json".to_owned(),
                    content_type: "application/json".to_owned(),
                    uncompressed_bytes: 1,
                    content_id: "00".repeat(32),
                },
            },
            snapshots: Vec::new(),
            transaction_details: Vec::new(),
            configuration: FixtureConfiguration {
                requested_transaction_count_per_source: 0,
                source_count: 0,
                common_transaction_share_basis_points: 0,
                witness_variant_share_basis_points: 0,
            },
            output_directory: PathBuf::new(),
        };
        let error = validate_manifest(&manifest, FixtureProfile::Functional)
            .expect_err("unsupported manifest should fail");
        assert!(
            error
                .to_string()
                .contains("unsupported fixture manifest version")
        );
    }

    #[test]
    fn performance_source_count_is_bounded() {
        let error = export(ExportOptions {
            profile: FixtureProfile::Performance,
            output_root: temporary_output_root("invalid-source-count"),
            transaction_count: 10,
            source_count: MAX_PERFORMANCE_SOURCES + 1,
        })
        .expect_err("too many performance sources should fail");
        assert!(error.to_string().contains("source count must be between"));
    }
}
